### ISSUE TITLE
.travis.yml file should (perhaps) be changed for "new" app / testing apps

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab-app-cutter#5]
I think the current content of the `.travis.yml` file is not correct.
I believe it is taken from an existing app, but I am not sure.

First, it tries to install the app, including `precommit` and `testing` packages, however, these do not exist for the current app.
In the end, it is probably fine if these are simply removed?
Perhaps some guide-lines should be written concerning how to test AiiDA Lab Apps as well?

Do we have a common or "normal" way of testing apps? - Making sure the AiiDA db env is loaded, how to test Jupyter notebooks, etc?

**Comment by ltalirz** [comment]
Thanks for noticiing

> In the end, it is probably fine if these are simply removed?

Yes.

> Do we have a common or "normal" way of testing apps?

Not currently, but there are ways: https://github.com/computationalmodelling/nbval
As the number and complexity of apps grows, providing guidance on testing them is becoming more and more important and would be a great addition.

**Comment by CasperWA** [comment]
> Not currently, but there are ways: https://github.com/computationalmodelling/nbval
> As the number and complexity of apps grows, providing guidance on testing them is becoming more and more important and would be a great addition.

Great - I was about to make another issue, where we could discuss this over time, but maybe this repo is not the correct one? Should I make a Docs document instead?

**Comment by ltalirz** [comment]
> I was about to make another issue, where we could discuss this over time, but maybe this repo is not the correct one? 

Fine to keep it here for the moment.

> Should I make a Docs documented instead?

???

**Comment by CasperWA** [comment]
I will keep it here then. The document was meant to be a place where we could lay out the architecture/guidelines for testing apps.
